version: "2"

services:
  web:
    hostname: "MDVA-%id%"
    image: docker.sparta.corp.magento.com:5000/m2:%img%
    ports:
      - "%ip_address%:80:80"
      - "%ip_address%:81:81"
      - "%ip_address%:3306:3306"
      - "%ip_address%:22:22"
    volumes:
      - ~/:/home/apache/
